AWSTemplateFormatVersion: "2010-09-09"

Description: Definition eines Amazon MQ Brokers (AKO, version 0.1)

Parameters:

    SSHAccessCIDR1:
        Type: String
        Default: 172.16.0.0/12
    SSHAccessCIDR2:
        Type: String
        Default: 10.0.0.0/8


Resources:
    MyFistBroker:
        Type: AWS::AmazonMQ::Broker
        Properties:
            AutoMinorVersionUpgrade: "false"
            BrokerName: MyFirstBroker
            Users: 
            -   ConsoleAccess: "true"
                Groups: [group1]
                Username: user1
                Password: user1user1user1
            -   ConsoleAccess: "false"
                Groups: [group2]
                Username: user2
                Password: user2user2user2
            # Notwendigkeit für diese Konfiguration analysieren    
            # Configuration: ConfigurationId
            DeploymentMode: SINGLE_INSTANCE
            EngineType: ActiveMQ
            EngineVersion: "5.15.0"
            HostInstanceType: mq.t2.micro
            Logs: 
                General: "true"
                Audit: "false"
            # was wird hier ggf. genau gemacht
            # Auswirkungen auf Verfügbarkeit
            MaintenanceWindowStartTime:
                DayOfWeek: SATURDAY
                TimeOfDay: "23:00"
                TimeZone: Europe/Berlin
            PubliclyAccessible: "false"            
            SecurityGroups: 
            -   !Ref BrokerSecurityGroup
            # Optional: 1 subnet für SINGLE_INSTANCE
            SubnetIds: 
            -   !ImportValue VPC1-AZ1Subnet1
        
    BrokerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow access to broker
            VpcId: !ImportValue VPC1-VPC-ID
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 61617
              ToPort: 61617
              CidrIp: !Ref SSHAccessCIDR1
            - IpProtocol: tcp
              FromPort: 61617
              ToPort: 61617
              CidrIp: !Ref SSHAccessCIDR2 
            - IpProtocol: tcp
              FromPort: 8162
              ToPort: 8162
              CidrIp: !Ref SSHAccessCIDR1
            - IpProtocol: tcp
              FromPort: 8162
              ToPort: 8162
              CidrIp: !Ref SSHAccessCIDR2 



            
    
